config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             :path => '',
             :path_names => {
               :sign_in => 'login',
               :sign_out => 'logout',
               :edit => 'profile'},
             :controllers => {
               :omniauth_callbacks => 'omniauth_callbacks',
               :registrations => 'registrations'
               
             }

  resources :services do
    resources :orders, only: [:create]
    resources :reviews, only: [:create, :destroy]
    collection do
      get 'all'
    end
  end

  resources :charges
  resources :orders, only: [:show]

  # These are hacks.  Should use a nested resource
  # resources :users do
  #   member 'orders'
  # end
  get '/user_orders'=> 'orders#user_orders'
  get '/user_sales'=> 'orders#user_sales'
  get '/search', to: 'search#search'

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user
  has_many :orders
  has_many :reviews

  has_attached_file :image, { styles: { medium: "300x300",
                                        small: "230x140",
                                        thumb: "100x100" },
                              preserve_files: true
                            }

  validates :title, presence: true, length: { maximum: 80 }
  validates :description, presence: true, length: { maximum: 1200 } 
  validates :price, presence: true
  validates :delivery_time, presence: false
  validates :revisions, presence: false
  validates :requirements, presence: true, length: { maximum: 250 }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

  def self.search(query)
    where("title LIKE ? OR description LIKE ? OR requirements LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show, :all]

  def index
    @services = current_user.services
  end

  def all
    @services = Service.all
  end

  def show
    @is_buyer = Order.where("service_id = ? AND user_id = ?", @service.id, current_user.id).present? if current_user

    @reviews = @service.reviews
    @reviewed = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @service = current_user.services.build
  end

  def create
    @service = current_user.services.build(service_params)

    if @service.save
      redirect_to @service
    else
      # previous @service object is passed to template so errors can appear on the form
      render :new
    end
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service
    else
      render :edit
    end
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :description, :price, :requirements, :image)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def service_quantity_opts(service)
    price = service.price
    [].tap do |a|
      1.upto(5) do |i|
        text = "#{i} ($#{price * i})"
        a << [text, i]
      end
    end
  end
end

app/views/services/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= @service.new_record? ? "Create your gig" : "Edit your gig" %></h2>
  </div>
  <div class="panel-body">
    <%= form_for @service do |f| %>

      <% if @service.errors.any? %> 
        <div class="alert alert-info">
          <h3>
            Fix the following <%= pluralize(@service.errors.count, "error") %>
            before continuing: 
          </h3>
          <ul>
            <% @service.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <label>Gig Title</label>
        <%= f.text_area :title, placeholder: "Ex: I will do something I am really good at", rows: "2", class:"form-control" %>
      </div>

      <div class="form-group">
        <label>Description</label>
        <%= f.text_area :description, rows: "5", class:"form-control" %>
      </div>

      <div class="form-group">
        <label>Pricing</label>
        <div class="select-control">
          <%= f.select :price, [["$6", "6"], ["$12", "12"], ["$18", "18"], ["$24", "24"]], class:"form-control" %>
        </div>          
      </div>

      <div class="form-group">
        <label>Requirements</label>
        <%= f.text_area :requirements, rows: "5", class:"form-control" %>
      </div>

      <div class="form-group">
        <label>Add Photo</label>
        <%= f.file_field :image %>
      </div>

      <hr/>

      <%= f.submit (@service.new_record? ? "Publish Gig" : "Update Gig"), class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/services/all.html.erb
<div class="row">

  <div class="col-md-12">

    <div class="panel panel-default">
      <div class="panel-heading">

        <div class="row">
          <div class="col-md-6">
            <h3>All Gigs</h3>
          </div>
        </div>

        <div class="panel-body">
          <% @services.each do |service| %>
            <div class="row">
              <div class="col-md-2">
                <a href="<%= service_path(service) %>">
                  <%= image_tag service.image.url(:thumb) %>
                </a>
              </div>
              <div class="col-md-7">
                <h4><%= link_to service.title, service_path(service) %></h4>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <center>
          <%= image_tag avatar_url(current_user), class: "img-circle img-responsive img-seller-avatar" %>
          <h3><%= current_user.fullname %></h3>
        </center>
      </div>

      <div class="panel-body">
        <%= current_user.description %>
      </div>

    </div>
  </div>

  <div class="col-md-8">
    <% if flash[:notice].present? %>
      <div class="row">
        <div class="col-md-8">
          <div class="alert alert-success" role="alert">
            <h3>Welcome <%= current_user.firstname %></h3>
          </div>
        </div>
      </div>
    <% end %>

    <div class="panel panel-default">
      <div class="panel-heading">

        <div class="row">
          <div class="col-md-6">
            <h3>My Gigs</h3>
            <%= link_to "Create a Gig", new_service_path, class: "btn btn-success" %>
          </div>
        </div>

        <div class="panel-body">
          <% @services.each do |service| %>
            <div class="row">
              <div class="col-md-2">
                <%= image_tag service.image.url(:thumb) %>
              </div>
              <div class="col-md-7">
                <h4><%= service.title %></h4>
              </div>
              <div class="col-md-3">
                <%= link_to "Update", edit_service_path(service), class: "btn btn-default pull-right" %>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/services/new.html.erb
<%= render 'form' %>

app/views/services/show.html.erb
<%
meta title: "Sixerr Gig",
     description: "#{@service.title}",
     keywords: %w(keyword1 keyword2 keyword3),
     og: {
      image: "#{@service.image.url}"
     }
%>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><%= @service.title %></h3>
        </div>
        <div class="panel-body">
          <center>
            <%= image_tag(@service.image.url(:medium), :class => "img-responsive") %>
          </center>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>About This Gig</h3>
        </div>
        <div class="panel-body">
          <p><%= @service.description %></p>
        </div>
      </div>

      <%= render 'reviews/form' if @is_buyer && !@reviewed %>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>Reviews</h3>
        </div>
        <%= render 'reviews/list' %>

      </div>
    </div>
    <div class="col-md-4">
      <%= render 'orders/form' %>

      <div class="panel panel-default">
        <div class="panel-body">
          <h5 class="pull-left">
            <%= pluralize(@reviews.count, "Buyer Review") %>
          </h5>

          <h4 class="pull-right"><%= @service.average_rating %> </h4>
             <div id="average_rating" class="pull-right img-average-rating-stars"></div>
             <!-- <%= asset_path('ratings.png', :class => "img-rating-stars") %> -->
        </div>
      </div>
      <center>
        <div id="share"></div>
        <!-- <ul class="soc">
            <li><a class="soc-facebook" href="#"></a></li>
            <li><a class="soc-twitter" href="#"></a></li>
            <li><a class="soc-google" href="#"></a></li>
            <li><a class="soc-linkedin soc-icon-last" href="#"></a></li>
        </ul> -->
        <br>
      </center>
      <div class="panel panel-default">
        <div class="panel-heading">
          <center>
              <%= image_tag avatar_url(@service.user), class:"img-circle img-responsive img-seller-avatar" %>
              <h3><%= @service.user.fullname %></h3>
          </center>
        </div>
        <div class="panel-body">
          <%= @service.user.description %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @service.average_rating %>
  });

  // $("#share").jsSocials({
  //     showLabel: false,
  //     showCount: false,
  //     shares: ["facebook", "twitter", "googleplus", "linkedin", "pinterest"]
  //  });
</script>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>