config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             :path => '',
             :path_names => {
               :sign_in => 'login',
               :sign_out => 'logout',
               :edit => 'profile'},
             :controllers => {
               :omniauth_callbacks => 'omniauth_callbacks',
               :registrations => 'registrations'
               
             }

  resources :services do
    resources :orders, only: [:create]
    resources :reviews, only: [:create, :destroy]
    collection do
      get 'all'
    end
  end

  resources :charges
  resources :orders, only: [:show]

  # These are hacks.  Should use a nested resource
  # resources :users do
  #   member 'orders'
  # end
  get '/user_orders'=> 'orders#user_orders'
  get '/user_sales'=> 'orders#user_sales'
  get '/search', to: 'search#search'

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

end

app/views/shared/_debug.html.erb
<!-- ENV: <%= Rails.env %> -->
<!-- Figaro env: <%= Figaro.env.fig_env %> -->

app/views/shared/_gigcard.html.erb
<div class="col-md-3">
  <%= link_to(service) do %>
    <div class="gig-card">
      <center>
        <%= image_tag service.image.url(:small)%>
        <h4>
          <%= service.title %>
        </h4>
        <h3>
          $<%= service.price %>
        </h3>
      </center>
    </div>
  <% end %>
</div>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
    </script>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to app_name, root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <%= form_tag(search_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
      <%= text_field_tag :q, params[:q], class:"form-control", placeholder: "Find Services" %>
      <%= submit_tag "Search", :name => nil, class:"btn btn-default" %>
    <% end %>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Services", all_services_path %></li>

      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span>
              <%= image_tag avatar_url(current_user), class: "navbar-avatar img-circle" %>
              &nbsp;
              <%= current_user.firstname %>
            </span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">Buying</li>
            <li><%= link_to "My Orders", user_orders_path %></li>

            <li class="dropdown-header">Selling</li>
            <li><%= link_to "My Gigs", services_path %></li>
            <li><%= link_to "Manage Sales", user_sales_path %></li>
            <li><%= link_to "Create a Gig", new_service_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Join", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <%= link_to "Start Selling", new_user_session_path, class: 'btn btn-default navbar-btn' %>
      <% end %>

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>