config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             :path => '',
             :path_names => {
               :sign_in => 'login',
               :sign_out => 'logout',
               :edit => 'profile'},
             :controllers => {
               :omniauth_callbacks => 'omniauth_callbacks',
               :registrations => 'registrations'
               
             }

  resources :services do
    resources :orders, only: [:create]
    resources :reviews, only: [:create, :destroy]
    collection do
      get 'all'
    end
  end

  resources :charges
  resources :orders, only: [:show]

  # These are hacks.  Should use a nested resource
  # resources :users do
  #   member 'orders'
  # end
  get '/user_orders'=> 'orders#user_orders'
  get '/user_sales'=> 'orders#user_sales'
  get '/search', to: 'search#search'

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :service

  validates :quantity, presence: true
  validates :price, presence: true
  validates :total_price, presence: true
  validates :service_id, presence: true

  before_save :set_order_price

  private

  def set_order_price
    self.total_price = self.quantity * self.price
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def user_orders
    @orders = current_user.orders
  end

  def user_sales
    @services = current_user.services
  end

  private

  def order_params
    params.require(:order).permit(:quantity, :price, :total_price,
                                  :service_id, :stripe_email, :currency, :stripe_customer_id)
  end  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <center>
      <%= form_tag charges_path, id:'chargeForm' do %>
        <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        </article>

        <%= hidden_field_tag 'stripeToken' %>
        <%= hidden_field_tag 'stripeEmail' %>
        <%= hidden_field_tag 'price', @service.price %>
        <%= hidden_field_tag 'total_price', {id:"total_price"} %>
        <%= hidden_field_tag 'service_id', @service.id %>
        <%= hidden_field_tag 'description', @service.title %>

        <button id="btn-order" class="btn btn-primary btn-lg btn-order" type="button">
          Order Now ($<%= @service.price %>)
        </button>

        <script>
          var handler = StripeCheckout.configure({
            key: '<%= Rails.configuration.stripe[:publishable_key] %>',
            token: function(token, arg) {
              document.getElementById("stripeToken").value = token.id;
              document.getElementById("stripeEmail").value = token.email;
              document.getElementById("chargeForm").submit();
            }
          });

          document.getElementById('btn-order').addEventListener('click', function(e){
            var quantity = $('#quantity').val();
            var total_price = parseInt((quantity * "<%= @service.price %>") + "00");
            $('#total_price').val(total_price);
            handler.open({
              name: "Chris MP",
              description: "<%= @service.title %>",
              amount: total_price
            });
            e.preventDefault();
          });
        </script>
      </center>
      <hr>
      <h5 class="pull-left">Basic Gig Quantity</h5>
      <div class="form-group pull-right">
        <div class="select-control">
          <%= select_tag(:quantity, options_for_select(service_quantity_opts(@service)), {id: "quantity"}) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/user_orders.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <center>
          <%= image_tag avatar_url(current_user), class: "img-circle img-responsive img-seller-avatar" %>
          <h3><%= current_user.fullname %></h3>
        </center>
      </div>
      <div class="panel-body">
        <%= current_user.description %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>My Orders</h3>
      </div>
      <div class="panel-body">

        <% if flash[:notice].present? %>
          <div class="row">
            <div class="col-md-8">
              <div class="alert alert-success" role="alert">
                <h3>Purchase completed!  Woo hoo!</h3>
              </div>
            </div>
          </div>
        <% end %>


        <% @orders.each do |order| %>
          <div class="row">
            <div class="col-md-2">
              <%= link_to service_path(order.service) do %>
                <%= image_tag order.service.image.url(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= link_to service_path(order.service) do %>
                <h4><%= order.service.title %></h4>
              <% end %>
            </div>
            <div class="col-md-2">
              <h5>Quantity: <%= order.quantity %> <br/>
                Price: $<%= order.price %></h5>
            </div>
            <div class="col-md-2">
              <h5><%= order.created_at.strftime('%b %d, %Y') %></h5>
            </div>
            <div class="col-md-3">
              <h5>Total Price: $<%= order.total_price %></h5>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/user_sales.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>My Sales</h3>
      </div>

      <% if flash[:notice].present? %>
        <div class="row">
          <div class="col-md-10">
            <h2>Purchase completed!  Woo hoo!</h2>
          </div>
        </div>
      <% end %>

      <div class="panel-body">
        <% if flash[:notice].present? %>
          <div class="row">
            <div class="col-md-10">
              <h2>Purchase completed!  Woo hoo!</h2>
            </div>
          </div>
        <% end %>

        <% if current_user.orders.length == 0 %>
          <div class="row">
            <div class="col-md-8">
              <h3>You have no orders at this time</h3>
            </div>
          </div>
        <% end %>

        <% @services.each do |service| %>
          <% service.orders.each do |order| %>
            <div class="row">
              <div class="col-md-2">
                <%= link_to service_path(order.service) do %>
                  <%= image_tag order.service.image.url(:thumb) %>
                <% end %>
              </div>
              <div class="col-md-2">
                <%= link_to service_path(order.service) do %>
                  <h4><%= order.service.title %></h4>
                <% end %>
              </div>
              <div class="col-md-2">
                <h5>Qty: <%= order.quantity %> <br/>
                  Price: $<%= order.price %></h5>
              </div>
              <div class="col-md-2">
                <span><%= image_tag avatar_url(order.user), class:"navbar-avatar img-circle" %></span>
                <h5><%= order.user.fullname %></h5>
              </div>
              <div class="col-md-2">
                <h5><%= order.created_at.strftime('%b %d, %Y') %></h5>
              </div>
              <div class="col-md-2">
                <h5>Total: $<%= order.total_price %></h5>
              </div>
            </div>
            <hr>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>